blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¡ Ideas"
    url: https://github.com/jeremybower/tmpl/discussions/categories/feature-ideas
    about: Share ideas for new features
  - name: "ğŸ™ Q&A"
    url: https://github.com/jeremybower/tmpl/discussions/support
    about: Ask the community for help
